### ISSUE TITLE
implement callbacks

### ISSUE THREAD

**Issue by aniketmaurya** [gradsflow/gradsflow#103]
# 🚘 Callback Roadmap

- [x] #120 - @aniketmaurya #121
- [ ] #122 - @aniketmaurya https://github.com/gradsflow/gradsflow/pull/151
- [x] Tensorboard #123
- [x] Comet #125
- [x] WandB Callback #124
- [x] CSV Logger - @aniketmaurya #116

**Comment by gagan3012** [comment]
Hey I can work on this

**Comment by aniketmaurya** [comment]
awesome, pls let me know if you need any help or need discussion.

**Comment by arvindmuralie77** [comment]
Hey @aniketmaurya , can I take up the tensorboard callback?

**Comment by aniketmaurya** [comment]
> Hey @aniketmaurya , can I take up the tensorboard callback?

Sure @arvindmuralie77 , pls go ahead.
