### ISSUE TITLE
Error while using the Text classifier

### ISSUE THREAD

**Issue by kingafy** [gradsflow/gradsflow#11]
dataloader = _PatchDataLoader(dataloader)
TypeError: __init__() missing 1 required positional argument: 'stage' for  the code:-
from gradsflow.autoclassifier import text

from flash.core.data.utils import download_data
from flash.text import TextClassificationData

# 1. Create the DataModule
download_data("https://pl-flash-data.s3.amazonaws.com/imdb.zip", "./data/")

datamodule = TextClassificationData.from_csv(
    "review",
    "sentiment",
    train_file="data/imdb/train.csv",
    val_file="data/imdb/valid.csv",
    backbone="prajjwal1/bert-medium",
    
)

suggested_conf = dict(
    optimizers=["adam"],
    lr=(5e-4, 1e-3),
)

model = AutoTextClassifier(datamodule,
                           suggested_backbones=['sgugger/tiny-distilbert-classification'],
                           suggested_conf=suggested_conf,
                           max_epochs=1,
                           optimization_metric="val_accuracy",
                           timeout=30)

print("AutoTextClassifier initialised!")
model.hp_tune()

**Comment by aniketmaurya** [comment]
hi @kingafy, which Pytorch Lightning version are you using?

could you try `pip install -U pytorch-lightning==1.4.0` and check if the issue is still coming?

**Comment by kingafy** [comment]
Thanks it worked. Its a really cool  thing you guys have come up with.
 Also can you add more documentation to this as to which hyperparams can we pass apart from optimizer and lr. Is there any documentation on that? Also does it support more than two classes. Is it using hugging face framework behind the hood?

**Comment by aniketmaurya** [comment]
Glad that you liked it 😀! Yes, we have [documentation](https://docs.gradsflow.com/), we are still improving it.

Yes, huggingface is being used behind the hood 🤗 and multiple classes are also supported. Let me know if you face any issue in that.
