### ISSUE TITLE
cannot import name 'AutoImageClassifier'

### ISSUE THREAD

**Issue by zh-my** [gradsflow/gradsflow#132]
When I use "from gradsflow import AutoImageClassifier"
bug: cannot import name 'AutoImageClassifier'

**Comment by aniketmaurya** [comment]
hi @zh-my, thanks for reporting this issue. May I know which Gradsflow version are you using?

**Comment by aniketmaurya** [comment]
Closing this since this issue is not reproducible. Feel free to open the issue if you are still facing this issue.
Thanks
