### ISSUE TITLE
Add a conda installation option

### ISSUE THREAD

**Issue by sugatoray** [gradsflow/gradsflow#138]
I believe, adding a `conda` installation option for `gradsflow` will be helpful for growth and adoption of the library. I have started the work on it already. Once the :bulb: [**PR**](https://github.com/conda-forge/staged-recipes/pull/17215) gets approved and merged, you will have gradsflow on conda-forge.

```sh
conda install -c conda-forge gradsflow
```
## :no_entry: :fire: Roadblock to conda-forge packaging
However, there seems to be a problem: it appears that this library is somewhat tightly coupled with `comet_ml` (which has a proprietary license -- NOT OpenSource). If you could work on making this a weak coupling, or better yet make `comet_ml` optional (even for tests), that would allow us to make gradsflow available on conda-forge.

**Comment by sugatoray** [comment]
cc: @aniketmaurya

**Comment by aniketmaurya** [comment]
Thanks for the Great suggestion @sugatoray 😄 
Would you like to work on making `comet_ml` optional?

**Comment by sugatoray** [comment]
@aniketmaurya Although, I would like to, I may not have time to do that now. So, if you, or someone else wants to work on it, please go ahead.

**Comment by aniketmaurya** [comment]
No issues! Let me prioritize this.

**Comment by sugatoray** [comment]
@aniketmaurya I believe this issue should be left open until gradsflow is made available on conda-forge. Once it is available I will push a fresh PR to update the docs, readme, etc.

**Comment by sugatoray** [comment]
@aniketmaurya Also, please push a new release to PyPI. The conda-forge version is built/updated based on the official PyPI release version(s).

**Comment by aniketmaurya** [comment]
hi @sugatoray, I have made a post-release on PyPI for Gradsflow https://pypi.org/project/gradsflow/.
is there any blocker in `conda-forge` integration?

**Comment by sugatoray** [comment]
@aniketmaurya GradsFlow is now available on conda-forge. :100: :sparkles: 

> Link to [LinkedIn announcement :arrow_upper_right: ](https://www.linkedin.com/posts/sugatoray_gradsflow-pytorch-condaforge-activity-6877822261026463744-w5Xh). 

![image](https://user-images.githubusercontent.com/10201242/146628519-60bd0ea0-7db4-4a38-b96a-e61ed3ba244e.png)
