### ISSUE TITLE
remove `tests` folder from PyPI package

### ISSUE THREAD

**Issue by sugatoray** [gradsflow/gradsflow#140]
The PyPI package of `gradsflow` has `tests` folder. Typically the tests folder should not be included in the package (one key reason is: this keeps the package leaner and the user has nothing to do with the tests either), unless they are kept their for some specific reason by design (_this deviates from common-practice though_).

![image](https://user-images.githubusercontent.com/10201242/146520886-674dbc8d-ce70-46a8-a71f-9f3939d9b734.png)

This was discovered while working on this PR: https://github.com/conda-forge/staged-recipes/pull/17215

**Comment by aniketmaurya** [comment]
thank you for reporting this @sugatoray! I will raise a PR to remove `tests` from pip distributions
