### ISSUE TITLE
(PYL-W0613) Function contains unused argument

### ISSUE THREAD

**Issue by aniketmaurya** [gradsflow/gradsflow#165]
## Description
An unused argument can lead to confusions. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/gradsflow/gradsflow/issue/PYL-W0613/occurrences/](https://deepsource.io/gh/gradsflow/gradsflow/issue/PYL-W0613/occurrences/)

**Comment by skp-github** [comment]
It is something that needs to be fixed (i mean it's not done yet)?

**Comment by aniketmaurya** [comment]
Hi @skp-github! first of all, thanks for checking the issues. This issue is intentional and we have to add rules in Deepsource to ignore this.
You can help us by raising a PR for this. Here is a [documentation](https://deepsource.io/docs/setup-analysis/#silencing-a-specific-issue) on how to silence this issue.

**Comment by skp-github** [comment]
@aniketmaurya Thank you for the reply. I will try to see and raise a PR for the same(I'm kind a new to the project just need to get my self familiar), can you suggest few links to understand more about gradsflow ?. Is there any list of expected/required features list which i can work on as well ?. Also I think you will happy to know that I work for a research lab which is using gradflow for a lot of neurophysiological research :)

**Comment by aniketmaurya** [comment]
@skp-github Some of the resources to learn more about Gradsflow are -
* 📚 [Official documentation](https://docs.gradsflow.com/en/latest/)
* 🧑‍💻 [Release Blogpost](https://towardsdatascience.com/gradsflow-democratizing-ai-with-automl-9a8a75d6b7ea)
* 🎥 [Hacktoberfest 2021 Presentation](https://youtu.be/lVtxXyCAZ-4?t=2663)

__(If you find something unexpected feel free to reach out in our community [Slack channel](https://join.slack.com/t/gradsflow/shared_invite/zt-ulc0m0ef-xstzyowuTgYceVmFbJlBmg))__

For a new feature, maybe you can check [this issue](https://github.com/gradsflow/gradsflow/issues/161).


Also, it is great to know that Gradsflow is being used at a research lab. If you don't mind I would love to know more about it.

**Comment by skp-github** [comment]
@aniketmaurya I'm sorry if i understood it incorrectly but this specific issue seems to be resolved already (i.e skipcp signal is already there tuner/automodel.py line 77 ) but i can see anti pattern issues at https://deepsource.io/gh/gradsflow/gradsflow/issues?category=antipattern&analyzer=all&page=1, do you want me to fix them and generate a PR because, unused variable one is not fixed yet. Please guide me on this. Also, sure i will connect with you over the slack channel and I can give you details about the lab and other details :)

**Comment by aniketmaurya** [comment]
I think most of the issues in deepsource are false positive or intentional so I would recommend to leave that one. There are some other issues/feature request if you would like to work on?

**Comment by skp-github** [comment]
@aniketmaurya for the first part, i fixed two small anti pattern issues, i have few questions about the PR process (it's fine if you don't accept the PR once i generate it but i will have an idea how the flow works, i will ask you my questions on slack). Second part, yes i would love to work on the feature request or issues if you have some kind list or anything similar(if you are not talking about the ones which are already listed as issues ).
