### ISSUE TITLE
Automatic Task Selection

### ISSUE THREAD

**Issue by aniketmaurya** [gradsflow/gradsflow#41]
#### Is your feature request related to a problem? Please describe.
Create Tasks directly from `AutoClassifier` instead of explicitly calling `AutoImageClassification` or `AutoTextSummarization`

#### Describe the solution you'd like

```python
model=AutoClassification(datamodule, data_type="image")  # expected `data_type`-> image, text, infer
model.hp_tune()
```

**Comment by gagan3012** [comment]
Can we have it like:

```python
model=AutoClassification(datamodule, task="summasrisation")  # expected `data_type`-> image, text, infer
model.hp_tune()
```

**Comment by aniketmaurya** [comment]
@gagan3012 yes, but we already have something like `from gradsflow import AutoSummarization` and the summarization task doesn't align with the classification task 😄 

How about -

```python
autotask = AutoTask(datamodule, task='summarization')
```

or 
```python
# way-1
autotask = AutoTask(datamodule, data_type='infer')

# way-2
autotask = AutoTask(datamodule, data_type='text')
```

For way-1, we can auto infer the task type.

Let me know your thoughts on this.

**Comment by gagan3012** [comment]
Hi, 
I think the 
```python
autotask = AutoTask(datamodule, task='summarization')
```
is better

**Comment by aniketmaurya** [comment]
cool! would you like to create a PR for this?
