### ISSUE TITLE
pass config to `build_model` during object initialization

### ISSUE THREAD

**Issue by aniketmaurya** [gradsflow/gradsflow#56]
#### Is your feature request related to a problem? Please describe.
Right now there is no way to allow configs (other than hparams) to pass into `build_model` method.

#### Describe the solution you'd like
```python
automodel = AutoImageClassification(datamodule=datamodule, build_model_conf = {"pretrained": True })
automodel.hp_tune()
```

**Comment by kajal-puri** [comment]
Hi, I'm interested to take up this issue. Can you assign this to me?
